### ISSUE TITLE
Firebase Auth

### ISSUE THREAD

**Issue by rafael-figueiredo-alves** [rafael-figueiredo-alves/eFirebase#2]

**Comment by rafael-figueiredo-alves** [comment]
Firebase Auth has been sucessfully implemented with most of the functions that are provided from Firebase rest API

**Comment by Nhatsave** [comment]
Saudacoes ilustre, espero que essa mensagem o encontre bem, aqui e Ernesto, novo na linguagem FreePascal.
Estou tentando desenvolver um aplicativo desktop que faz autenticacao no firebase usando lazarus, ate aqui consegui instalar o eFirebase usando o boss, como pode ver o meu boss.json

{
	"name": "project1",
	"description": "",
	"version": "1.0.0",
	"homepage": "",
	"mainsrc": "./src",
	"projects": [],
	"dependencies": {
		"github.com/hashload/horse": "^3.1.3",
		"github.com/viniciussanchez/dataset-serialize-adapter-restrequest4delphi": "^1.0.1",
		"github.com/viniciussanchez/restrequest4delphi": "^v4.0.2",
		"https://github.com/rafael-figueiredo-alves/efirebase": "^v1.0.0"
	}
}
mas acontece que ao compilar da me erros pois nao tem os modulos:

uses
  eFirebase.Types,
  System.Classes,
  System.JSON,
  Data.DB;

type 

usados pela unit eFirebase.Interfaces;

e nao tenho ideia de onde conseguir esses arquivos. 

Agradeco qualquer ajuda,

**Comment by rafael-figueiredo-alves** [comment]
Opa, olá, Ernesto. Vou averiguar o problema aqui, mas tenho quase certeza que é porque projetei dentro do Delphi, e como não estou com Lazarus para testar, não sabia se seria necessário algum ajuste. Acho que vai ser necessário alguns ajustes. Vou revisar e volto aqui para falar quando estiver pronto para você testar, OK? Obrigado por sua colaboração.

**Comment by rafael-figueiredo-alves** [comment]
> Saudacoes ilustre, espero que essa mensagem o encontre bem, aqui e Ernesto, novo na linguagem FreePascal. Estou tentando desenvolver um aplicativo desktop que faz autenticacao no firebase usando lazarus, ate aqui consegui instalar o eFirebase usando o boss, como pode ver o meu boss.json
> 
> { "name": "project1", "description": "", "version": "1.0.0", "homepage": "", "mainsrc": "./src", "projects": [], "dependencies": { "github.com/hashload/horse": "^3.1.3", "github.com/viniciussanchez/dataset-serialize-adapter-restrequest4delphi": "^1.0.1", "github.com/viniciussanchez/restrequest4delphi": "^v4.0.2", "https://github.com/rafael-figueiredo-alves/efirebase": "^v1.0.0" } } mas acontece que ao compilar da me erros pois nao tem os modulos:
> 
> uses eFirebase.Types, System.Classes, System.JSON, Data.DB;
> 
> type
> 
> usados pela unit eFirebase.Interfaces;
> 
> e nao tenho ideia de onde conseguir esses arquivos.
> 
> Agradeco qualquer ajuda,

Ernesto, eu realizei alguns ajustes. Gostaria que você realizasse testes e me informe se funcionou para ti ou não. Teste a nova versão 1.0.1 (#11 )
